replaced tabs with spaces

diff --git a/src/lib/pre-install b/src/lib/pre-install
--- a/src/lib/pre-install
+++ b/src/lib/pre-install
@@ -6,17 +6,17 @@ pushd `dirname $0` > /dev/null 2>&1;
 # find path to php
 PHP_BIN=`which php`
 if [ -z "$PHP_BIN" ]; then
-	echo 'PHP executable not found, enter path: '
-	read PHP_BIN
+  echo 'PHP executable not found, enter path: '
+  read PHP_BIN
 fi
 
 
 # run pre-install.php
 if [ -x "$PHP_BIN" ]; then
-	$PHP_BIN ./pre-install.php
+  $PHP_BIN ./pre-install.php
 else
-	echo 'PHP executable not found, unable to run pre-install.php'
-	exit 1;
+  echo 'PHP executable not found, unable to run pre-install.php'
+  exit 1;
 fi
 
 
